### ISSUE TITLE
Unable to run WCT due to IEDriverServer download issue

### ISSUE THREAD

**Issue by Klathmon** [Polymer/web-component-tester#206]
Having an issue where WCT will fail to run because it can't download IEDriverServer.

It looks like it's trying to download 2.47 and 2.46 at the same time...

the url is http://selenium-release.storage.googleapis.com/2.47/IEDriverServer_x64_2.46.0.zip (which doesn't exist).

I'm on Windows 10, io.js v 2.5.0, IE Edge and IE11 are both installed and running fine.

And this happens even if IE is not specified as a test browser.

If I go and manually download http://selenium-release.storage.googleapis.com/2.47/IEDriverServer_x64_2.47.0.zip (note the last 2.47 compared to the 2.46) and put it in the correct location and unzip it, it works until I do an npm update.

Full log below:

    Starting Selenium server for local browsers
    ----------
    selenium-standalone installation starting
    ----------
    ---
    selenium install:
    from: http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar
    to: C:\Users\gregb\Projects\StitchPics\node_modules\web-component-tester\node_modules\wct-local\node_modules\selenium-standalone\.selenium\selenium-server\2.47.1-server.jar
    ---
    chrome install:
    from: http://chromedriver.storage.googleapis.com/2.16/chromedriver_win32.zip
    to: C:\Users\gregb\Projects\StitchPics\node_modules\web-component-tester\node_modules\wct-local\node_modules\selenium-standalone\.selenium\chromedriver\2.16-x64-chromedriver
    ---
    ie install:
    from: http://selenium-release.storage.googleapis.com/2.47/IEDriverServer_x64_2.46.0.zip
    to: C:\Users\gregb\Projects\StitchPics\node_modules\web-component-tester\node_modules\wct-local\node_modules\selenium-standalone\.selenium\iedriver\2.46.0-x64-IEDriverServer.exe
    [20:33:50] 'wct:local' errored after 14 s
    [20:33:50] Error: Could not request headers from http://selenium-release.storage.googleapis.com/2.47/IEDriverServer_x64_2.46.0.zip:

**Comment by beast** [comment]
Having the same issue here. Could someone help looking into this? Thanks.

**Comment by pubudu91** [comment]
I'm also having the same issue.

<pre><code>Starting Selenium server for local browsers
----------
selenium-standalone installation starting
----------
---
selenium install:
from: http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar
to: F:\xampp\htdocs\PropNetsVis\node_modules\web-component-tester\node_modules\wct-local\node_modules\selenium-standalone\.selenium\selenium-server\2.45.0-server.jar
---
chrome install:
from: http://chromedriver.storage.googleapis.com/2.16/chromedriver_win32.zip
to: F:\xampp\htdocs\PropNetsVis\node_modules\web-component-tester\node_modules\wct-local\node_modules\selenium-standalone\.selenium\chromedriver\2.16-x64-chromedriver
---
ie install:
from: http://selenium-release.storage.googleapis.com/2.45/IEDriverServer_x64_2.46.0.zip
to: F:\xampp\htdocs\PropNetsVis\node_modules\web-component-tester\node_modules\wct-local\node_modules\selenium-standalone\.selenium\iedriver\2.46.0-x64-IEDriverServer.exe
---
File from http://chromedriver.storage.googleapis.com/2.16/chromedriver_win32.zip has already been downloaded
[19:32:57] 'wct:local' errored after 6.07 min
[19:32:57] Error: Could not request headers from http://selenium-release.storage.googleapis.com/2.45/IEDriverServer_x64_2.46.0.zip:
</code></pre>

**Comment by SimonRingeisen** [comment]
same here

'wct:local' errored after 16 s
Error: Could not request headers from http://selenium-release.storage.googleapis.com/2.47/IEDriverServer_x64_2.46.0.zip:

**Comment by jclx** [comment]
Issue looks like a type in: node_modulesweb-component-tester/node_modules/wct-local/node_modules/selenium-standalone/lib/compute-download-urs.js
    ie: util.format(
      urls.ie,
      opts.drivers.ie.baseURL,
      minorSeleniumVersion, // wrong value should use ie version
      getIeDriverArchitecture(opts.drivers.ie.arch),
      opts.drivers.ie.version
    )

should be:
    ie: util.format(
      urls.ie,
      opts.drivers.ie.baseURL,
      opts.drivers.ie.version.slice(0, opts.drivers.ie.version.lastIndexOf('.'));,
      getIeDriverArchitecture(opts.drivers.ie.arch),
      opts.drivers.ie.version
    )

**Comment by JulianLaval** [comment]
+1 !

**Comment by Bismuth76** [comment]
:+1: !

**Comment by vvo** [comment]
I have fixed this, this should be bumped in wct-local: selenium-standalone@4.6.1

have fun, let me know

**Comment by azakus** [comment]
@vvo Thanks for the notice!

**Comment by starryeyez024** [comment]
In my Polymer project, in the file: `polymer/node_modules/web-component-tester/node_modules/wct-local/package.json`, it specifies using selenium-standalone 4.6.1 or greater and I still have this issue. 

*package.json:*

```
  "dependencies": {
    "chalk": "^1.1.1",
    "cleankill": "^1.0.0",
    "freeport": "^1.0.4",
    "launchpad": "^0.4.4",
    "lodash": "^3.0.1",
    "selenium-standalone": "^4.6.1",
    "which": "^1.0.8"
  },
```

*error message:*

```
^MBP:polymer $ gulp test:local
[15:11:20] Using gulpfile ~/Sites/polymer/gulpfile.js
[15:11:20] Starting 'wct:local'...
Installing and starting Selenium server for local browsers
----------
selenium-standalone installation starting
----------
---
selenium install:
from: http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar
to: /Users/---/Sites/polymer/node_modules/web-component-tester/node_modules/wct-local/node_modules/selenium-standalone/.selenium/selenium-server/2.47.1-server.jar
---
chrome install:
from: http://chromedriver.storage.googleapis.com/2.18/chromedriver_mac32.zip
to: /Users/---/Sites/polymer/node_modules/web-component-tester/node_modules/wct-local/node_modules/selenium-standalone/.selenium/chromedriver/2.18-x64-chromedriver
---
File from http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar has already been downloaded
---
File from http://chromedriver.storage.googleapis.com/2.18/chromedriver_mac32.zip has already been downloaded
-----
selenium-standalone installation finished
-----
No Java runtime present, requesting install.
[15:11:22] 'wct:local' errored after 1.41 s
[15:11:22] Error: Another Selenium process is already running
```

**Comment by vvo** [comment]
Open another issue in selenium standalone thx

**Comment by sebs** [comment]
Not working for me as well.

**Comment by sebs** [comment]
A install of that Java package changes nothing about that error.

**Comment by domrongpon-tanpaibul** [comment]
Anyone know if config is allow to disable downloading these files everytime wct is run? Technially they only needed to download once and it could be seperate command to update them manually if needed. Any idea?

**Comment by sebs** [comment]
I do not think it is a bug we should file and work on in selenium. It is the wct that is not working.

@vvo is there a way to fix that problem on a late (2014) mac with all upgraded?

**Comment by vvo** [comment]
If you have an issue with selenium-standalone, Open another issue in the project
